# Generated by Django 5.1.2 on 2024-10-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Pending'), (3, 'On Hold')], default=3),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Pending'), (3, 'On Hold')], default=31),
        ),
    ]
