# Generated by Django 5.1.2 on 2024-10-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_issue_status_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
